steps:
- id: 'branch name'
  name: 'alpine'
  entrypoint: 'sh'  
  args: 
  - '-c'
  - | 
      echo "***********************"
      echo "$BRANCH_NAME"
      echo "***********************"

# [START tf-init-and-plan]
- id: 'tf init and plan'
  name: 'hashicorp/terraform:latest'
  entrypoint: 'sh'
  args: 
  - '-c'
  - |
      echo "********** DIRECTORY **********"
      pwd
      echo "********** CONTENTS ***********"
      ls -R
      echo "********** GIT DIFF ***********"
      git diff --name-only HEAD^ HEAD
      echo "*******************************"
      TARGETS_DIR=$(git diff --name-only HEAD^ HEAD | grep -E "^(environments|components).*\.tf.*" | sed -E "s/environments\/(dev|prod|stg)/components/g" | xargs -I@ dirname @ | uniq)
      ENV=""
      case "$BRANCH_NAME" in
        develop) ENV="dev" ;;
        release) ENV="stg" ;;
        main)    ENV="prod" ;;
      esac

      for dir in $TARGETS_DIR
      do
        if [-d $dir]; then
          cd ${dir}
          COMPONENTS_VAR_DIR=$(echo $dir | sed -E "s/components/environments\/$ENV/g")
          CLOUD_VAR_DIR=$(dirname $COMPONENTS_VAR_DIR)
          ENV_VAR_DIR=$(dirname $CLOUD_VAR_DIR)
          DEFAULT_VAR_DIR=$(dirname $ENV_VAR_DIR)
          COMPONENTS=$(basename COMPONENTS_VAR_DIR)

          echo "*************** TERRAFORM INIT ****************************"
          echo "******* At environment: $ENV, Target: $dir ********"
          echo "***********************************************************"
          terraforn init \
            --backend-config=prefix=${ENV}/${COMPONENTS} -migrate-state
          terraform plan \
            -var-file="${DEFAULT_VAR_DIR}/terraform.tfvars" \
            -var-file="${ENV_VAR_DIR}/terraform.tfvars" \
            -var-file="${CLOUD_VAR_DIR}/terraform.tfvars" \
            -var-file="${COMPONENTS_VAR_DIR}/terraform.tfvars"
          cd ../../../
        fi
      done
  secretEnv: ['TF_VAR_aws_access_key', 'TF_VAR_aws_secret_key']
      
availableSecrets:
  secretManager:
  - versionName: projects/181997179469/secrets/paloma-cicd-secret-aws-access-key/versions/latest
    env: 'TF_VAR_aws_access_key'
  - versionName: projects/181997179469/secrets/paloma-cicd-secret-aws-secret-key/versions/latest
    env: 'TF_VAR_aws_secret_key'