steps:
- id: 'branch name'
  name: 'alpine'
  entrypoint: 'sh'  
  args: 
  - '-c'
  - | 
      echo "***********************"
      echo "$BRANCH_NAME"
      echo "***********************"

# [START tf-init-and-plan]
- id: 'tf init and plan'
  name: 'hashicorp/terraform:latest'
  entrypoint: 'sh'
  args: 
  - '-c'
  - |
      echo "********** DIRECTORY **********"
      pwd
      echo "********** CONTENTS ***********"
      ls -R
      echo "********** GIT DIFF ***********"
      # CloudBuildはデフォルトでshallow cloneをするため最新のcommit履歴しかない。fetchで過去の履歴を取得する
      git fetch --unshallow > /dev/null
      git diff --name-only HEAD^ HEAD
      echo "*******************************"
      targets_dir=$(git diff --name-only HEAD^ HEAD | grep -E "^(environments|components).*\.tf.*" | sed -E "s/environments\/(dev|prod|stg)/components/g" | xargs -I@ dirname @ | uniq)
      env=""
      case "$BRANCH_NAME" in
        develop) env="dev" ;;
        release) env="stg" ;;
        main)    env="prod" ;;
      esac
      echo "targets_dir:" $targets_dir
      echo "env:" $env

      for dir in ${targets_dir}
      do
          cd ${dir}
          components_var_dir=$(echo $dir | sed -E "s/components/environments\/$env/g")
          cloud_var_dir=$(dirname $components_var_dir)
          env_var_dir=$(dirname $cloud_var_dir)
          default_var_dir=$(dirname $env_var_dir)
          components=$(basename $components_var_dir)

          echo "*************** TERRAFORM INIT ****************************"
          echo "******* At environment: $env, Target: $dir ********"
          echo "***********************************************************"
          terraform init \
            --backend-config=prefix=${env}/${components} -migrate-state
          terraform plan \
            -var-file="${default_var_dir}/terraform.tfvars" \
            -var-file="${env_var_dir}/terraform.tfvars" \
            -var-file="${cloud_var_dir}/terraform.tfvars" \
            -var-file="${components_var_dir}/terraform.tfvars"
          cd ../../../
      done
  secretEnv: ['TF_VAR_aws_access_key', 'TF_VAR_aws_secret_key']
      
availableSecrets:
  secretManager:
  - versionName: projects/181997179469/secrets/paloma-cicd-secret-aws-access-key/versions/latest
    env: 'TF_VAR_aws_access_key'
  - versionName: projects/181997179469/secrets/paloma-cicd-secret-aws-secret-key/versions/latest
    env: 'TF_VAR_aws_secret_key'